import fs from "node:fs";
import path from "node:path";

export interface WranglerConfigInput {
  projectName: string;
  dbId: string;
  previewDbId: string;
  /**
   * Whether to include the R2 bucket bindings. Defaults to true so the
   * committed placeholder config and teardown keep R2 wired. Set false when
   * setup runs without R2 file storage.
   */
  enableR2?: boolean;
}

const HEADER_COMMENT =
  "// Generated by scripts/first-time-setup.ts — real IDs are filled in by setup; teardown restores dummy values.";

/**
 * Builds the full wrangler.jsonc config object (top-level + "preview" env),
 * mirroring the committed wrangler.jsonc structure exactly.
 */
export function buildWranglerConfig(input: WranglerConfigInput): object {
  const { projectName, dbId, previewDbId, enableR2 = true } = input;

  const dbName = `${projectName}-db`;
  const bucketName = `${projectName}-bucket`;
  const previewDbName = `${dbName}-preview`;
  const previewBucketName = `${bucketName}-preview`;
  const workflowName = `${projectName}-example-workflow`;
  const previewWorkflowName = `${workflowName}-preview`;

  const r2Buckets = [{ binding: "BUCKET", bucket_name: bucketName }];
  const previewR2Buckets = [
    { binding: "BUCKET", bucket_name: previewBucketName },
  ];

  return {
    name: projectName,
    main: "workers/app.ts",
    compatibility_date: "2025-03-25",
    compatibility_flags: ["nodejs_compat"],
    assets: {
      directory: "build/client",
      binding: "ASSETS",
    },
    placement: {
      mode: "smart",
    },
    d1_databases: [
      {
        binding: "DATABASE",
        database_name: dbName,
        database_id: dbId,
        migrations_dir: "./drizzle",
      },
    ],
    ...(enableR2 ? { r2_buckets: r2Buckets } : {}),
    workflows: [
      {
        binding: "EXAMPLE_WORKFLOW",
        name: workflowName,
        class_name: "ExampleWorkflow",
      },
    ],
    ai: {
      binding: "AI",
    },
    observability: {
      logs: {
        enabled: true,
        head_sampling_rate: 1,
        invocation_logs: true,
        persist: true,
      },
    },
    workers_dev: true,
    preview_urls: true,
    env: {
      preview: {
        workers_dev: true,
        preview_urls: true,
        d1_databases: [
          {
            binding: "DATABASE",
            database_name: previewDbName,
            database_id: previewDbId,
            migrations_dir: "./drizzle",
          },
        ],
        ...(enableR2 ? { r2_buckets: previewR2Buckets } : {}),
        workflows: [
          {
            binding: "EXAMPLE_WORKFLOW",
            name: previewWorkflowName,
            class_name: "ExampleWorkflow",
          },
        ],
        ai: {
          binding: "AI",
        },
        observability: {
          logs: {
            enabled: true,
            head_sampling_rate: 1,
            invocation_logs: true,
            persist: true,
          },
        },
      },
    },
  };
}

/**
 * Writes the given config object to the repo-root wrangler.jsonc, prefixed
 * with a header comment explaining that the file is generated/restored by
 * scripts/first-time-setup.ts and scripts/teardown.ts.
 */
export function writeWranglerJsonc(config: object): void {
  const wranglerJsonPath = path.join(__dirname, "..", "..", "wrangler.jsonc");

  const jsonContent =
    `${HEADER_COMMENT}\n` + JSON.stringify(config, null, 2) + "\n";

  fs.writeFileSync(wranglerJsonPath, jsonContent);
}

/**
 * Dummy input used to regenerate the committed placeholder wrangler.jsonc
 * (fresh clone / after teardown). IDs are not real Cloudflare resource IDs,
 * but are well-formed enough for `wrangler types`, `vite build`, and local
 * D1 migrations to succeed against.
 */
export const DUMMY_INPUT: WranglerConfigInput = {
  projectName: "cf-saas-starter-react-router",
  dbId: "00000000-0000-0000-0000-000000000000",
  previewDbId: "00000000-0000-0000-0000-000000000000",
};
